// Copyright 2026 Soap Bucket LLC. Licensed under the Apache License, Version 2.0.
package codegen

import (
	"fmt"
	"strings"

	"github.com/clictl/cli/internal/models"
)

// GeneratePython produces a Python module string from a tool spec.
// Each action becomes a dataclass for params + an async function.
func GeneratePython(spec *models.ToolSpec) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`"""Auto-generated by clictl codegen
Tool: %s v%s`, spec.Name, spec.Version))
	if spec.Description != "" {
		b.WriteString(fmt.Sprintf(" - %s", spec.Description))
	}
	b.WriteString(fmt.Sprintf(`

Usage: clictl codegen %s --lang python
Docs:  clictl info %s
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional`, spec.Name, spec.Name))

	// Check if we need Literal
	needsLiteral := false
	for _, action := range spec.Actions {
		for _, p := range action.Params {
			if len(p.Values) > 0 {
				needsLiteral = true
				break
			}
		}
		if needsLiteral {
			break
		}
	}
	if needsLiteral {
		b.WriteString(", Literal")
	}
	b.WriteString("\n\n")

	// Auth env vars
	envVars := collectAuthEnvVars(spec)
	if len(envVars) > 0 {
		b.WriteString("# Required environment variables:\n")
		for _, env := range envVars {
			b.WriteString(fmt.Sprintf("#   %s\n", env))
		}
		b.WriteString("\n")
	}

	for _, action := range spec.Actions {
		if action.IsComposite() {
			continue
		}
		writePythonAction(&b, spec, &action)
	}

	return b.String()
}

func writePythonAction(b *strings.Builder, spec *models.ToolSpec, action *models.Action) {
	funcName := ToSnakeCase(action.Name)
	className := ToPascalCase(action.Name) + "Params"

	// Dataclass for params
	hasParams := len(action.Params) > 0
	if hasParams {
		b.WriteString("@dataclass\n")
		b.WriteString(fmt.Sprintf("class %s:\n", className))

		// Required params first, then optional
		var required, optional []models.Param
		for _, p := range action.Params {
			if p.Required {
				required = append(required, p)
			} else {
				optional = append(optional, p)
			}
		}

		for _, p := range required {
			pyType := pyTypeForParam(p)
			b.WriteString(fmt.Sprintf("    %s: %s\n", ToSnakeCase(p.Name), pyType))
			if p.Description != "" {
				b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", p.Description))
			}
		}
		for _, p := range optional {
			pyType := pyTypeForParam(p)
			defaultVal := "None"
			if p.Default != "" {
				defaultVal = pyDefaultValue(p)
			}
			b.WriteString(fmt.Sprintf("    %s: Optional[%s] = %s\n", ToSnakeCase(p.Name), pyType, defaultVal))
			if p.Description != "" {
				b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", p.Description))
			}
		}
		b.WriteString("\n\n")
	}

	// Async function
	method := "GET"
	if action.Method != "" {
		method = strings.ToUpper(action.Method)
	}
	url := spec.ResolveActionURL(action)

	if hasParams {
		b.WriteString(fmt.Sprintf("async def %s(params: %s) -> Any:\n", funcName, className))
	} else {
		b.WriteString(fmt.Sprintf("async def %s() -> Any:\n", funcName))
	}

	desc := action.Description
	if desc == "" {
		desc = action.Name
	}
	b.WriteString(fmt.Sprintf("    \"\"\"%s\n", desc))
	if url != "" {
		b.WriteString(fmt.Sprintf("\n    %s %s%s\n", method, url, action.Path))
	}
	b.WriteString("    \"\"\"\n")
	b.WriteString("    ...\n\n\n")
}

func pyTypeForParam(p models.Param) string {
	if len(p.Values) > 0 {
		quoted := make([]string, len(p.Values))
		for i, v := range p.Values {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		return "Literal[" + strings.Join(quoted, ", ") + "]"
	}
	return PyType(p.Type)
}

func pyDefaultValue(p models.Param) string {
	switch strings.ToLower(p.Type) {
	case "int", "integer":
		return p.Default
	case "float", "number":
		return p.Default
	case "bool", "boolean":
		if p.Default == "true" {
			return "True"
		}
		return "False"
	default:
		return fmt.Sprintf("%q", p.Default)
	}
}
