// Copyright 2026 Soap Bucket LLC. Licensed under the Apache License, Version 2.0.
package codegen

import (
	"fmt"
	"strings"

	"github.com/clictl/cli/internal/models"
)

// GenerateTypeScript produces a TypeScript module string from a tool spec.
// Each action becomes a typed interface + async function declaration.
func GenerateTypeScript(spec *models.ToolSpec) string {
	var b strings.Builder

	b.WriteString("// Auto-generated by clictl codegen\n")
	b.WriteString(fmt.Sprintf("// Tool: %s v%s", spec.Name, spec.Version))
	if spec.Description != "" {
		b.WriteString(fmt.Sprintf(" - %s", spec.Description))
	}
	b.WriteString("\n//\n")
	b.WriteString("// Usage: clictl codegen " + spec.Name + " --lang typescript\n")
	b.WriteString("// Docs:  clictl info " + spec.Name + "\n\n")

	// Collect all unique env vars for auth
	envVars := collectAuthEnvVars(spec)
	if len(envVars) > 0 {
		b.WriteString("// Required environment variables:\n")
		for _, env := range envVars {
			b.WriteString(fmt.Sprintf("//   %s\n", env))
		}
		b.WriteString("\n")
	}

	for _, action := range spec.Actions {
		if action.IsComposite() {
			continue // skip composite actions for now
		}
		writeTypeScriptAction(&b, spec, &action)
	}

	return b.String()
}

// GenerateTypeScriptDeclarations produces just the type declarations (no implementation).
// Used for MCP code mode system prompt injection.
func GenerateTypeScriptDeclarations(specs []*models.ToolSpec) string {
	var b strings.Builder
	b.WriteString("// Available API clients\n\n")

	for _, spec := range specs {
		httpActions := 0
		for _, a := range spec.Actions {
			if a.URL != "" || (spec.Server != nil && spec.Server.URL != "") {
				httpActions++
			}
		}
		if httpActions == 0 {
			continue
		}

		b.WriteString(fmt.Sprintf("// %s - %s\n", spec.Name, spec.Description))
		b.WriteString(fmt.Sprintf("declare const %s: {\n", ToCamelCase(spec.Name)))

		for _, action := range spec.Actions {
			if action.IsComposite() {
				continue
			}
			writeTypeScriptInlineDecl(&b, &action)
		}

		b.WriteString("}\n\n")
	}

	return b.String()
}

func writeTypeScriptAction(b *strings.Builder, spec *models.ToolSpec, action *models.Action) {
	ifaceName := ToPascalCase(action.Name) + "Params"
	funcName := ToCamelCase(action.Name)

	// Param interface
	hasParams := len(action.Params) > 0
	if hasParams {
		b.WriteString(fmt.Sprintf("export interface %s {\n", ifaceName))
		for _, p := range action.Params {
			if p.Description != "" {
				b.WriteString(fmt.Sprintf("  /** %s */\n", p.Description))
			}
			tsType := tsTypeForParam(p)
			optional := ""
			if !p.Required {
				optional = "?"
			}
			b.WriteString(fmt.Sprintf("  %s%s: %s\n", p.Name, optional, tsType))
		}
		b.WriteString("}\n\n")
	}

	// Function declaration with JSDoc
	if action.Description != "" {
		b.WriteString(fmt.Sprintf("/** %s */\n", action.Description))
	}

	// Method and URL comment
	method := "GET"
	if action.Method != "" {
		method = strings.ToUpper(action.Method)
	}
	url := spec.ResolveActionURL(action)
	if url != "" {
		b.WriteString(fmt.Sprintf("// %s %s%s\n", method, url, action.Path))
	}

	if hasParams {
		b.WriteString(fmt.Sprintf("export declare function %s(params: %s): Promise<any>\n\n", funcName, ifaceName))
	} else {
		b.WriteString(fmt.Sprintf("export declare function %s(): Promise<any>\n\n", funcName))
	}
}

func writeTypeScriptInlineDecl(b *strings.Builder, action *models.Action) {
	funcName := ToCamelCase(action.Name)
	desc := action.Description
	if desc == "" {
		desc = action.Name
	}

	// Build inline param type
	paramParts := []string{}
	for _, p := range action.Params {
		tsType := tsTypeForParam(p)
		optional := ""
		if !p.Required {
			optional = "?"
		}
		paramParts = append(paramParts, fmt.Sprintf("%s%s: %s", p.Name, optional, tsType))
	}

	paramType := ""
	if len(paramParts) > 0 {
		paramType = "params: { " + strings.Join(paramParts, ", ") + " }"
	}

	b.WriteString(fmt.Sprintf("  /** %s */\n", desc))
	b.WriteString(fmt.Sprintf("  %s(%s): Promise<any>\n", funcName, paramType))
}

func tsTypeForParam(p models.Param) string {
	if len(p.Values) > 0 {
		quoted := make([]string, len(p.Values))
		for i, v := range p.Values {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		return strings.Join(quoted, " | ")
	}
	return TSType(p.Type)
}

func collectAuthEnvVars(spec *models.ToolSpec) []string {
	seen := map[string]bool{}
	var result []string
	addEnv := func(auth *models.Auth) {
		if auth == nil {
			return
		}
		for _, e := range auth.Env {
			if !seen[e] {
				seen[e] = true
				result = append(result, e)
			}
		}
	}
	addEnv(spec.Auth)
	for _, a := range spec.Actions {
		addEnv(a.Auth)
	}
	return result
}
